platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

permissions_path = '../node_modules/react-native-permissions/ios'

# Add this line to define the permissions you are using
permissions = ['LocationWhenInUse', 'LocationAlways']

target 'AlphaCargo' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
    # Add this line!  This is the key fix.
    setup_permissions(installer, permissions)
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end

  target 'AlphaCargoTests' do
    inherit! :complete
  end
end